version: '3.8'
services:
  db:
    image: postgres:alpine
    restart: always
    hostname: db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 2s
      retries: 5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sensorsdb
    ports:
      - '5432:5432'
    volumes:
#      - db:/var/lib/postgresql/data # uncomment this if you want to persist data on a volume
      - ./migration/00_init.up.sql:/docker-entrypoint-initdb.d/init.sql
  sensord:
    build: .
    depends_on:
      db:
        condition: service_healthy
    image: sensord:latest
    environment:
      - DB_URL=postgres://postgres:postgres@db:5432/sensorsdb?sslmode=disable&search_path=sensors
      - DB_LOG=true
      - SENSOR_LISTEN_HTTP=:8080
      - ADMIN_LISTEN_HTTP=:9090
    ports:
      - '8080:8080'
      - '9090:9090'
volumes:
  db:
    driver: local